### ISSUE TITLE
measurement death loop

### ISSUE THREAD

**Issue by oetiker** [starzia/ClapIR#3]
about every third time I clap my hands (iPhone 4S) the software goes into a measurement loop and produces up to about 10 measurements in rapid fire succession ... even though there is no sound besides the clap which is long faded.

sometimes this behavior also leads to a crash of the app

**Comment by starzia** [comment]
@oetiker I recently made some changes that should alleviate this.  Please try version 1.4.0 of the app.

**Comment by oetiker** [comment]
works great! thanks! just tested with the iphone 14pro max
